### ISSUE TITLE
Server or AGP reloads break gyms

### ISSUE THREAD

**Issue by TheKnightKarim** [AnDwHaT5-Sidemods/AGP-Responged#39]
So gyms get closed after a restart or an agpreload, which I find very weird. I have talked to Avery about the issue but now I got github to work to post this here. Thank you again

**Comment by clienthax** [comment]
Agp reload reloads AGP to the base state, this is intended behaviour.

**Comment by AnDwHaT5** [comment]
This is not intended behavior you little shit reopening issue its annoying and so are u

**Comment by AnDwHaT5** [comment]
Fixed
