### ISSUE TITLE
[Issue Found] Pokemon randomly seem to sometimes start with less then full HP.

### ISSUE THREAD

**Issue by Jaded-Avaritia** [AnDwHaT5-Sidemods/AGP-Responged#47]
It seems to be random- but it was tested with Houndoom and 2/10 times it'd start with 1 to 2 HP less then full. Which makes sturdy and sash useless when it happens.

**Comment by AnDwHaT5** [comment]
Thats what happens when good old Avery doesnt refresh the stats after applying EVs and IVs. Fixed for the next update!
