### ISSUE TITLE
Badges given out for non-gym battles

### ISSUE THREAD

**Issue by UniversalSoul** [AnDwHaT5-Sidemods/AGP-Responged#49]
When gym leaders lose normal Pokemon battles, gym badges are being given out to random players who have previously challenged the gym. For example, Joe (a gym leader) battles Bob (a random player) and Joe loses, but Bill (a player who challenged Joe earlier in a gym battle) gets a gym badge. It has happened at least three times so far.

**Comment by AnDwHaT5** [comment]
Looks like I failed to refresh the queue when a leader won. This is now fixed for the next update, thanks for the report!
