### ISSUE TITLE
'Sometimes' challengers are unable to challenge gyms due to being already in a gym battle when they're not.

### ISSUE THREAD

**Issue by HackuJacku** [AnDwHaT5-Sidemods/AGP-Responged#5]
'Sometimes' you're unable to challenge a gym due to already being in a gym battle when you're not in a battle.

**Versions:**
* SpongeForge 1.12.2-2705-7.1.0-BETA-3361
* Luckperms 4.2.71
* Nucleus-1.5.3-S7.0-MC1.12.2-plugin
* AGP_Responged_S7.1.0-1.0.0_Beta2

**Reproducing:**
* Unable to reproduce when trying to reproduce.

* Have a player challenge the gym and win the battle.
* Have the player try and challenge the next gym.

**Image:**
* https://imgur.com/a/wxSyn39.png

**Expected Result:**
* Players will be able to challenge another gym without being getting this error.

**Comment by AnDwHaT5** [comment]
Should be fixed
