### ISSUE TITLE
Issue with mega stone, z-powers, and pixelmons

### ISSUE THREAD

**Issue by Peacefuldwarf** [AnDwHaT5-Sidemods/AGP-Responged#51]
Hi there! 
At this moment in time it's not possible for me to use mega evolutions or likewise after accepting a challenger battle (in other words gym leaders can't use "special abilities". Another problem is that once me and the challenge gets teleported to my gym, both of our pixelmons won't appear, and it's only possible to see the particle effects from each respective attack.

**Comment by AnDwHaT5** [comment]
Marking as duplicate, see #50
