### ISSUE TITLE
Issue with 7.0.6

### ISSUE THREAD

**Issue by Gelox1209** [AnDwHaT5-Sidemods/AGP-Responged#53]
Unable to add Pokemon to the temp gym pokemon list, and unable to start battles because of it:
`Error occurred while executing command 'acceptChallenge Dragon' for source EntityPlayerMP['Akanya'/116, l='world', x=456.41, y=132.25, z=-405.31]: com/pixelmonmod/pixelmon/util/helpers/SpriteHelper
10.06 21:49:33 [Server] INFO java.lang.NoClassDefFoundError: com/pixelmonmod/pixelmon/util/helpers/SpriteHelper
10.06 21:49:33 [Server] INFO at agp.andwhat5.Utils.getPixelmonSprite(Utils.java:455) ~[Utils.class:?]
10.06 21:49:33 [Server] INFO at agp.andwhat5.gui.ChooseTeamGui.getPokemonElement(ChooseTeamGui.java:218) ~[ChooseTeamGui.class:?]
10.06 21:49:33 [Server] INFO at agp.andwhat5.gui.ChooseTeamGui.constructChooseTeamPage(ChooseTeamGui.java:118) ~[ChooseTeamGui.class:?]
10.06 21:49:33 [Server] INFO at agp.andwhat5.gui.ChooseTeamGui.openChooseTeamGui(ChooseTeamGui.java:66) ~[ChooseTeamGui.class:?]
10.06 21:49:33 [Server] INFO at agp.andwhat5.commands.leaders.AcceptChallenge.execute(AcceptChallenge.java:73) ~[AcceptChallenge.class:?]
10.06 21:49:33 [Server] INFO at agp.andwhat5.commands.utils.PlayerOnlyCommand.execute(PlayerOnlyCommand.java:21) ~[PlayerOnlyCommand.class:?]
10.06 21:49:33 [Server] INFO at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2825-7.1.6]
10.06 21:49:33 [Server] INFO at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:340) ~[SimpleDispatcher.class:1.12.2-2825-7.1.6]
10.06 21:49:33 [Server] INFO at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:337) [SpongeCommandManager.class:1.12.2-2825-7.1.6]
10.06 21:49:33 [Server] INFO at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1156) [dh.class:?]
10.06 21:49:33 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:962) [pa.class:?]
10.06 21:49:33 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:941) [pa.class:?]
10.06 21:49:33 [Server] INFO at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
10.06 21:49:33 [Server] INFO at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
10.06 21:49:33 [Server] INFO at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193) [PacketPhaseUtil.class:1.12.2-2825-7.1.6]
10.06 21:49:33 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlk000(SourceFile:539) [hv$1.class:?]
10.06 21:49:33 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
10.06 21:49:33 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
10.06 21:49:33 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
10.06 21:49:33 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
10.06 21:49:33 [Server] INFO at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:307) [SpongeImplHooks.class:1.12.2-2825-7.1.6]
10.06 21:49:33 [Server] INFO at net.minecraft.server.MinecraftServer.redirect$onRun$zjo000(MinecraftServer.java:3970) [MinecraftServer.class:?]
10.06 21:49:33 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
10.06 21:49:33 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
10.06 21:49:33 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
10.06 21:49:33 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
10.06 21:49:33 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]`

`Error occurred while executing command 'gymPokemon Dragon' for source EntityPlayerMP['Akanya'/116, l='world', x=455.87, y=131.00, z=-407.63]: com/pixelmonmod/pixelmon/util/helpers/SpriteHelper
10.06 21:48:52 [Server] INFO java.lang.NoClassDefFoundError: com/pixelmonmod/pixelmon/util/helpers/SpriteHelper
10.06 21:48:52 [Server] INFO at agp.andwhat5.Utils.getPixelmonSprite(Utils.java:455) ~[Utils.class:?]
10.06 21:48:52 [Server] INFO at agp.andwhat5.gui.GymPokemonGui.getPokemonElement(GymPokemonGui.java:131) ~[GymPokemonGui.class:?]
10.06 21:48:52 [Server] INFO at agp.andwhat5.gui.GymPokemonGui.constructGymPokemonPage(GymPokemonGui.java:96) ~[GymPokemonGui.class:?]
10.06 21:48:52 [Server] INFO at agp.andwhat5.gui.GymPokemonGui.openGymPokemonGui(GymPokemonGui.java:49) ~[GymPokemonGui.class:?]
10.06 21:48:52 [Server] INFO at agp.andwhat5.commands.gyms.GymPokemon.execute(GymPokemon.java:16) ~[GymPokemon.class:?]
10.06 21:48:52 [Server] INFO at agp.andwhat5.commands.utils.PlayerOnlyCommand.execute(PlayerOnlyCommand.java:21) ~[PlayerOnlyCommand.class:?]
10.06 21:48:52 [Server] INFO at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2825-7.1.6]
10.06 21:48:52 [Server] INFO at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:340) ~[SimpleDispatcher.class:1.12.2-2825-7.1.6]
10.06 21:48:52 [Server] INFO at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:337) [SpongeCommandManager.class:1.12.2-2825-7.1.6]
10.06 21:48:52 [Server] INFO at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1156) [dh.class:?]
10.06 21:48:52 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:962) [pa.class:?]
10.06 21:48:52 [Server] INFO at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:941) [pa.class:?]
10.06 21:48:52 [Server] INFO at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
10.06 21:48:52 [Server] INFO at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
10.06 21:48:52 [Server] INFO at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193) [PacketPhaseUtil.class:1.12.2-2825-7.1.6]
10.06 21:48:52 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlk000(SourceFile:539) [hv$1.class:?]
10.06 21:48:52 [Server] INFO at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
10.06 21:48:52 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
10.06 21:48:52 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
10.06 21:48:52 [Server] INFO at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
10.06 21:48:52 [Server] INFO at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:307) [SpongeImplHooks.class:1.12.2-2825-7.1.6]
10.06 21:48:52 [Server] INFO at net.minecraft.server.MinecraftServer.redirect$onRun$zjo000(MinecraftServer.java:3970) [MinecraftServer.class:?]
10.06 21:48:52 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
10.06 21:48:52 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
10.06 21:48:52 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
10.06 21:48:52 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
10.06 21:48:52 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]`

**Comment by i9hdkill** [comment]
Try this branch for now:
https://github.com/i9hdkill/AGP-Responged

**Comment by AnDwHaT5** [comment]
Fixed for next update
