### ISSUE TITLE
Isue with agp-r announcement message

### ISSUE THREAD

**Issue by dagerix** [AnDwHaT5-Sidemods/AGP-Responged#55]
Issue with agp-r announcement message. In config message set to false still appears after reloading server. Then tried to set message time longer but no fix.
![image](https://user-images.githubusercontent.com/51381324/60399477-84026200-9b6d-11e9-964d-b8dfcf5a2d94.png)
![image](https://user-images.githubusercontent.com/51381324/60399502-d5125600-9b6d-11e9-9ad8-4f31cad5bf00.png)

Pixelmon version 7.0.6 ; AGP-Responged-S7.1.0-1.0.2.jar

**Comment by AnDwHaT5** [comment]
Lol I set up the tasks before the config loaded so it was always true. Fixed for next update. For now an /AGPReload might fix the announcements as it sets the tasks back up.
