### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by Smackzter** [AnDwHaT5-Sidemods/AGP-Responged#57]
Don't really have the details of the circumstances surrounding the error, but noticed this in the console. Generally I would imagine NullPointerExceptions only arise from logic errors though so it might be fixable from the stacktrace alone.

https://prnt.sc/ogaai4

**Comment by i9hdkill** [comment]
This happens when a gymn has for any reason no leaders or no gymn are existing

**Comment by AnDwHaT5** [comment]
Thanks for your input i9. Resolved for next update
